# Site settings
course_name: 16-785 Integrated Intelligence in Robotics, Vision-and-Language Planning
course_introduction: "Guillermo del Toro’s Pinocchio (2022), an Oscar nominated stop motion animation movie, took 15 years to make with a budget estimated over 35 million dollars. Another celebrated motion picture, Loving Vincent (2017), was fully hand painted by 152 artists and its production took 7 years, costing 5.5 million dollars. In this class, we will develop and experiment ideas to make such films using AI and robotics technologies. Course topics include language models, vision-language models, planning, and learning in the context of robotics. Examples of class projects include painted movies (robot painting), stop motion movies (manipulation), animation (text to image/video generation), directing (direction following), and robotic cinematography.  The final projects will be premiered at the end of the semester. "
course_description: "This course covers the topics on building cognitive intelligence for robotic systems. Cognitive capabilities constitute high-level, humanlike intelligence that exhibits reasoning or problem-solving skills. Such capabilities as semantic perception, language understanding, and task planning can be built on top of low-level robot autonomy that enables autonomous control of physical platforms. The topics generally bridge across multiple technical areas, for example, vision-language intersection and language-action/plan grounding.
This course is composed of 50% lectures and 50% seminar classes. Since this is a project-oriented course, we will put a special emphasis on learning research skills, e.g., problem formulation, literature review, ideation, evaluation planning, results analysis, and hypothesis verification.

Prerequisites: There are no explicit prerequisites for this class, but a general background knowledge in AI and machine learning is assumed."
course_goals: ""
course_semester: "Spring 2024"

baseurl: "/spring2024" # the subpath of your site, e.g. /blog/
url: "http://16785-VLP.github.io/" # the base hostname & protocol for your site

schoolname: "Bot Intelligence Group"
schoolurl: "https://cmubig.github.io"
# twitter_username: username 

address: |
    Carnegie Mellon University
    5000 Forbes Ave
    Pittsburgh, PA 15213, USA

### Do not change the followings unless you know what you are doing ###

# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
excerpt_separator: "<!--more-->"

include: ['_images', '_css']
exclude: ['develop']

dateformat: "%m/%d/%Y"

future: true
collections:
    events:
        output: true
    lectures:
        output: true
    assignments:
        output: true
    announcements:
        output: false


defaults:
  - scope:
      path: ""
      type: "assignments"
    values:
      layout: "assignment"
